# Generated by Django 2.1 on 2019-07-31 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vinmonopolet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alcohol_type', models.CharField(choices=[('Rødvin', 'Rødvin'), ('Hvitvin', 'Hvitvin'), ('Rosévin', 'Rosévin'), ('Musserende vin', 'Musserende vin'), ('Portvin', 'Portvin'), ('Champagne, brut', 'Champagne, brut'), ('Champagne, extra brut', 'Champagne, extra brut'), ('Champagne, rosé', 'Champagne, rosé'), ('Vodka', 'Vodka'), ('Gin', 'Gin'), ('Akevitt', 'Akevitt'), ('Rom', 'Rom'), ('Whisky', 'Whisky'), ('Brennevin, annet', 'Brennevin, annet'), ('Likør', 'Likør'), ('Vermut', 'Vermut')], default='Rødvin', max_length=30, verbose_name='Type of alcohol')),
                ('number', models.IntegerField(default=10, verbose_name='How many results?')),
            ],
        ),
    ]
