# Generated by Django 2.1 on 2019-12-14 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vinmonopolet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vinmonopolet',
            name='alcohol_type',
            field=models.CharField(choices=[('Rødvin', 'Rødvin'), ('Hvitvin', 'Hvitvin'), ('Rosévin', 'Rosévin'), ('Musserende vin', 'Musserende vin'), ('Portvin', 'Portvin'), ('Champagne, brut', 'Champagne, brut'), ('Champagne extra brut', 'Champagne extra brut'), ('Champagne, rosé', 'Champagne, rosé'), ('Vodka', 'Vodka'), ('Gin', 'Gin'), ('Akevitt', 'Akevitt'), ('Rom', 'Rom'), ('Whisky', 'Whisky'), ('Brennevin, annet', 'Brennevin, annet'), ('Likør', 'Likør'), ('Vermut', 'Vermut')], default='Rødvin', max_length=30, verbose_name='Type of alcohol'),
        ),
    ]
