# Generated by Django 2.1 on 2019-07-25 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.DecimalField(decimal_places=2, default=250, help_text='250 g gives a normal pizza, 300 g gives a large pizza', max_digits=10, verbose_name='Weight in grams')),
                ('water_percentage', models.DecimalField(decimal_places=2, default=65, help_text='57%-70%', max_digits=10)),
                ('number', models.DecimalField(decimal_places=2, default=3, max_digits=10, verbose_name='Number of pizzas')),
            ],
        ),
    ]
